name: Build & Test

on:
  push:
    branch: ["main"]
  pull_request:
    branch: ["main"]

env:
  ARCHITECTURE: 'x64'
  PYTHON_VERSION: '3.10'

jobs:
  build-dev:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          architecture: ${{ env.ARCHITECTURE }}
          cache: pipenv
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev

  check-code-style:
    runs-on: ubuntu-latest
    needs: build-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          architecture: ${{ env.ARCHITECTURE }}
          cache: pipenv
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv

      - name: Check code style
        run: pipenv run check-style

  unit-test:

    runs-on: ubuntu-latest
    needs: build-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          architecture: ${{ env.ARCHITECTURE }}
          cache: pipenv
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv

      - name: Unit test
        run: pipenv run unit-test
