name: Test KleptomanIOC

on:
  push:
    branch: ["main"]
  pull_request:
    branch: ["main"]

env:
  PYTHON_VERSION: '3.10'
  ARCHITECTURE: 'x64'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          architecture: ${{ env.ARCHITECTURE }}
          cache: pipenv
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - run: "ls -lA"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kleptomanioc-build
          path: ./

      - run: "ls -lA ~/.local/share"

      - run: "ls -lA ~/.local/share/virtualenvs"

  unit-test:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          architecture: ${{ env.ARCHITECTURE }}
          cache: pipenv
          python-version: ${{ env.PYTHON_VERSION }}

      # - name: Download build artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: kleptomanioc-build
      #     path: ./

      - run: "ls -la"

      - run: "ls -la ~/.local"

      - run: "ls -lA ~/.local/share/virtualenvs"

      - name: Unit test
        run: pipenv run unit-test



